# Generated by Django 5.2.17 on 2026-09-28 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permissiondeniedlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('repair_ticket_created', 'New repair ticket'), ('low_negative_feedback', 'Low-rated customer feedback (2 stars or fewer)')], max_length=40)),
                ('via_email', models.BooleanField(default=True)),
                ('via_whatsapp', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='accounts.role')),
            ],
            options={
                'ordering': ['event_key', 'role__label'],
                'unique_together': {('event_key', 'role')},
            },
        ),
    ]
