# Generated by Django 5.2.17 on 2026-09-28 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notificationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='via_inapp',
            field=models.BooleanField(default=True, help_text="Show in the header's notification bell for this role."),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_key',
            field=models.CharField(choices=[('repair_ticket_created', 'New repair ticket'), ('low_negative_feedback', 'Low-rated customer feedback (2 stars or fewer)'), ('rental_approved', 'Customer approved a rental agreement'), ('repair_approved', 'Customer approved a repair estimate'), ('payment_received', 'A payment was recorded (invoice or repair bill settled)')], max_length=40),
        ),
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('repair_ticket_created', 'New repair ticket'), ('low_negative_feedback', 'Low-rated customer feedback (2 stars or fewer)'), ('rental_approved', 'Customer approved a rental agreement'), ('repair_approved', 'Customer approved a repair estimate'), ('payment_received', 'A payment was recorded (invoice or repair bill settled)')], max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
