# Generated by Django 5.2.17 on 2026-09-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_party_whatsapp_checked_at_party_whatsapp_verified'),
        ('portal', '0002_portalaccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_delivery_logs', to='parties.party')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
