# Generated by Django 6.1.1 on 2026-09-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('compatible_brands', models.JSONField(blank=True, default=list, help_text='List of brand names this part fits.')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(max_length=80)),
                ('processor', models.CharField(blank=True, max_length=40)),
                ('hsn', models.CharField(blank=True, help_text='Leave blank if no HSN applies -- product_code covers it instead.', max_length=12)),
                ('condition', models.CharField(default='New', max_length=20)),
                ('product_code', models.CharField(help_text='VC-LAP-#### / VC-ACC-#### -- generated at creation.', max_length=32, unique=True)),
            ],
            options={
                'ordering': ['brand', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='StockPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('shop', 'Shop'), ('online', 'Online')], max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('segment', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software')], max_length=10)),
                ('charge', models.PositiveIntegerField()),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.part')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('spec', models.CharField(max_length=80)),
                ('mrp', models.PositiveIntegerField()),
                ('sell_price', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='PartStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.part')),
                ('stock_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_stock', to='catalog.stockpoint')),
            ],
            options={
                'unique_together': {('part', 'stock_point')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('stock_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.stockpoint')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.variant')),
            ],
            options={
                'unique_together': {('variant', 'stock_point')},
            },
        ),
    ]
