# Generated by Django 5.2.17 on 2026-10-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="location",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
