# Generated by Django 5.2.17 on 2026-10-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_stock_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpoint",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stockpoint",
            name="gstin",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="stockpoint",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
