# Generated by Django 6.1.1 on 2026-09-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('opening', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particulars', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('in', 'Cash in'), ('out', 'Cash out')], max_length=3)),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'cash entries',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particulars', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('in', 'Credit'), ('out', 'Debit')], max_length=3)),
                ('amount', models.PositiveIntegerField()),
                ('reconciled', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.bankaccount')),
            ],
            options={
                'verbose_name_plural': 'bank entries',
                'ordering': ['date', 'id'],
            },
        ),
    ]
