# Generated by Django 6.1.1 on 2026-09-06 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
