# Generated by Django 5.2.17 on 2026-10-03 23:23

import django.db.models.deletion
from django.db import migrations, models


def mark_default_account(apps, schema_editor):
    # one business account for now: the first existing one becomes the default
    BankAccount = apps.get_model("accounting", "BankAccount")
    first = BankAccount.objects.order_by("id").first()
    if first and not BankAccount.objects.filter(is_default=True).exists():
        BankAccount.objects.filter(pk=first.pk).update(is_default=True)



class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
        ("sales", "0006_move_repair_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bankentry",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_entry",
                to="sales.invoice",
            ),
        ),
        migrations.AddField(
            model_name="bankentry",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="UTR / UPI ref / cheque no. -- what the statement shows.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="cashentry",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_entry",
                to="sales.invoice",
            ),
        ),
        migrations.RunPython(mark_default_account, migrations.RunPython.noop),
    ]
