# Generated by Django 5.2.17 on 2026-10-03 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_invoice_postings"),
        ("sales", "0008_refunds_and_advance"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankentry",
            name="refund",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_entry",
                to="sales.refund",
            ),
        ),
        migrations.AddField(
            model_name="cashentry",
            name="refund",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_entry",
                to="sales.refund",
            ),
        ),
    ]
