# Generated by Django 6.1.1 on 2026-09-07 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='tickets',
            field=models.PositiveIntegerField(default=0, help_text='Support tickets raised during the tenure -- kept in sync with RentalIssue count.'),
        ),
        migrations.CreateModel(
            name='RentalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Resolved', 'Resolved')], default='Open', max_length=12)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rental_issues', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='rentals.rental')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
    ]
