# Generated by Django 5.2.17 on 2026-10-03 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_notificationrule_via_inapp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_layout",
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_layout",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier the frontend renders by, e.g. 'kpi-sales-revenue'.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("kpi", "KPI card"),
                            ("chart", "Chart"),
                            ("list", "List"),
                            ("table", "Table"),
                            ("panel", "Panel"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        blank=True,
                        choices=[("line", "Line"), ("bar", "Bar"), ("donut", "Donut")],
                        help_text="Only for kind=chart.",
                        max_length=10,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("stock", "Stock"),
                            ("sales", "Sales"),
                            ("repairs", "Repairs"),
                            ("rentals", "Rentals"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "data_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Keys of the dashboard summary response this widget reads.",
                    ),
                ),
                (
                    "respects_filters",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the date/channel filter bar changes this widget's figures.",
                    ),
                ),
                (
                    "link_page",
                    models.CharField(
                        blank=True,
                        help_text="Page the widget's 'View …' link opens, e.g. 'inventory'.",
                        max_length=32,
                    ),
                ),
                ("default_order", models.PositiveSmallIntegerField(default=0)),
                ("default_width", models.PositiveSmallIntegerField(default=3)),
                ("default_height", models.PositiveSmallIntegerField(default=1)),
                (
                    "default_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Per-widget options, e.g. {"limit": 6}.',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["default_order", "key"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_width__gte", 1), ("default_width__lte", 12)
                        ),
                        name="dashboardwidget_width_in_grid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("default_height__gte", 1)),
                        name="dashboardwidget_height_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardLayoutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("width", models.PositiveSmallIntegerField(default=3)),
                ("height", models.PositiveSmallIntegerField(default=1)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Overrides merged over the widget's default_settings.",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="dashboard.dashboardlayout",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="dashboard.dashboardwidget",
                    ),
                ),
            ],
            options={
                "ordering": ["layout", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="dashboardlayout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role__isnull", False), ("user__isnull", True)),
                    models.Q(("role__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="dashboardlayout_single_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardlayoutitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("width__gte", 1), ("width__lte", 12)),
                name="dashboardlayoutitem_width_in_grid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardlayoutitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("height__gte", 1)),
                name="dashboardlayoutitem_height_positive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dashboardlayoutitem",
            unique_together={("layout", "widget")},
        ),
    ]
