# Generated by Django 6.1.1 on 2026-09-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_label', models.CharField(help_text="Free-text device description, e.g. 'Dell Latitude 5420'.", max_length=120)),
                ('monthly_fee', models.PositiveIntegerField()),
                ('start', models.DateField()),
                ('tenure_months', models.PositiveIntegerField()),
                ('months_paid', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('tickets', models.PositiveIntegerField(default=0, help_text='Support tickets raised during the tenure.')),
                ('last_payment', models.DateField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='parties.party')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
    ]
