# Generated by Django 5.2.17 on 2026-09-16 06:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_tickets_rentalissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=48, unique=True)),
                ('serial_number', models.CharField(max_length=80, unique=True)),
                ('brand', models.CharField(max_length=40)),
                ('model_name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
        migrations.AddField(
            model_name='rental',
            name='agreement_code',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending customer approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RentalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('snapshot', models.JSONField(default=dict, editable=False)),
                ('token_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=12)),
                ('source', models.CharField(blank=True, choices=[('customer', 'Customer via secure link'), ('admin', 'Admin on behalf of customer'), ('superadmin', 'Super Admin override')], max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_approvals_decided', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='rentals.rental')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_approvals_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='RentalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('agreement_created', 'Agreement created'), ('approval_link_created', 'Approval link created'), ('approval_decided', 'Approval decided'), ('modified_after_approval', 'Modified internally after approval')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_events', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='rentals.rentalapproval')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rentals.rental')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RentalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.PositiveIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_lines', to='rentals.rentalasset')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rentals.rental')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rentalapproval',
            constraint=models.UniqueConstraint(fields=('rental', 'version'), name='unique_rental_approval_version'),
        ),
        migrations.AddConstraint(
            model_name='rentalapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('rental',), name='one_pending_rental_approval'),
        ),
        migrations.AddConstraint(
            model_name='rentalapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('rental',), name='one_approved_rental_approval'),
        ),
        migrations.AddConstraint(
            model_name='rentalline',
            constraint=models.UniqueConstraint(fields=('rental', 'asset'), name='one_asset_per_rental_agreement'),
        ),
    ]
