# Generated by Django 5.2.17 on 2026-09-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_approval_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending customer approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalevent',
            name='event_type',
            field=models.CharField(choices=[('agreement_created', 'Agreement created'), ('approval_link_created', 'Approval link created'), ('approval_decided', 'Approval decided'), ('modified_after_approval', 'Modified internally after approval'), ('agreement_cancelled', 'Agreement cancelled'), ('agreement_closed', 'Agreement closed')], max_length=32),
        ),
    ]
