# Generated by Django 5.2.17 on 2026-09-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_reconcile_legacy_rentals_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapproval',
            name='decided_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalapproval',
            name='decided_user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
