# Generated by Django 5.2.17 on 2026-10-03 22:23

import django.db.models.deletion
import rentals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0008_activate_legacy_rentals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalline",
            name="accessories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"name": "Charger", "serial": ""}]',
            ),
        ),
        migrations.AddField(
            model_name="rentalline",
            name="checks",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{check_key: true/false} for CHECKS.",
            ),
        ),
        migrations.AddField(
            model_name="rentalline",
            name="condition_notes",
            field=models.TextField(
                blank=True, help_text="Cosmetic condition: scratches, dents, wear."
            ),
        ),
        migrations.AddField(
            model_name="rentalline",
            name="handover_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentalline",
            name="handover_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalline",
            name="warranty_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rentalline",
            name="warranty_months",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Blank = the whole tenure.", null=True
            ),
        ),
        migrations.AddField(
            model_name="rentalline",
            name="warranty_terms",
            field=models.TextField(
                blank=True,
                help_text="The shop's own warranty conditions for this device.",
            ),
        ),
        migrations.AddField(
            model_name="rentalline",
            name="working_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Staff confirm the device was tested and is in working condition.",
            ),
        ),
        migrations.AlterField(
            model_name="rentalevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("agreement_created", "Agreement created"),
                    ("approval_link_created", "Approval link created"),
                    ("approval_decided", "Approval decided"),
                    ("modified_after_approval", "Modified internally after approval"),
                    ("agreement_cancelled", "Agreement cancelled"),
                    ("agreement_closed", "Agreement closed"),
                    ("handover_updated", "Device handover details changed"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="RentalLinePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("front", "Front (screen side)"),
                            ("lid", "Back / lid"),
                            ("left", "Left side"),
                            ("right", "Right side"),
                            ("base", "Bottom / base"),
                            ("serial", "Serial number label"),
                            ("keyboard", "Keyboard"),
                            ("screen_on", "Screen switched on"),
                            ("accessory", "Accessories"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=120)),
                ("image", models.FileField(upload_to=rentals.models.rental_photo_path)),
                ("content_type", models.CharField(max_length=40)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="rentals.rentalline",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
