# Generated by Django 5.2.17 on 2026-10-03 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_stockpoint_address"),
        ("rentals", "0009_device_handover"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalasset",
            name="source_stock_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.stockpoint",
            ),
        ),
        migrations.AddField(
            model_name="rentalasset",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rental_assets",
                to="catalog.variant",
            ),
        ),
    ]
