# Generated by Django 5.2.17 on 2026-10-03 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_stockpoint_address"),
        ("rentals", "0010_asset_from_inventory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalasset",
            name="returned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentalasset",
            name="returned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.stockpoint",
            ),
        ),
        migrations.AddField(
            model_name="rentalasset",
            name="returned_to_stock_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
