# Generated by Django 5.2.17 on 2026-09-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='customer_classification',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business / Corporate'), ('dealer', 'Dealer')], default='individual', max_length=12),
        ),
    ]
