# Generated by Django 5.2.17 on 2026-09-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_classify_existing_dealers'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='whatsapp_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='whatsapp_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
