# Generated by Django 5.2.17 on 2026-09-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_party_whatsapp_checked_at_party_whatsapp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='portal_access_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
