# Generated by Django 5.2.17 on 2026-10-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0005_party_portal_access_revoked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.CharField(
                choices=[("whatsapp", "WhatsApp"), ("email", "Email"), ("sms", "SMS")],
                max_length=10,
            ),
        ),
    ]
