# Generated by Django 6.1.1 on 2026-09-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Payment link sent', 'Payment link sent'), ('Overdue', 'Overdue')], default='Payment link sent', max_length=20)),
                ('pay_method', models.CharField(blank=True, max_length=40)),
                ('recurring_interval', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('6-month', 'Every 6 months')], max_length=10)),
                ('recurring_next', models.DateField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='parties.party')),
                ('stock_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='catalog.stockpoint')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField(help_text='Snapshot of sell price at the time of sale.')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='catalog.variant')),
            ],
        ),
    ]
