# Generated by Django 5.2.17 on 2026-10-03 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_invoice_payment_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="10-digit Indian mobile number the link was sent to.",
                        max_length=10,
                    ),
                ),
                (
                    "upi_check",
                    models.CharField(
                        choices=[
                            ("verified", "Verified by lookup"),
                            ("staff_confirmed", "Confirmed with customer by staff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Rupees, at the time the link was sent."
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                (
                    "provider_link_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("provider_payment_id", models.CharField(blank=True, max_length=64)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_links",
                        to="sales.invoice",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_links_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
