# Generated by Django 5.2.17 on 2026-10-03 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_stockpoint_address"),
        ("rentals", "0007_rentalapproval_decided_ip_and_more"),
        ("repairs", "0006_alter_repairticketevent_event_type"),
        ("sales", "0004_payment_link_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="rental",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="rentals.rental",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="repair_reopen",
            field=models.OneToOneField(
                blank=True,
                help_text="Set for the bill of a reopened (follow-up) repair visit.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="repairs.repairreopen",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="repair_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="repairs.repairticket",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="source",
            field=models.CharField(
                choices=[("sale", "Sale"), ("repair", "Repair"), ("rental", "Rental")],
                db_index=True,
                default="sale",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="price",
            field=models.IntegerField(
                help_text="Snapshot of the unit price at the time of invoicing."
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_items",
                to="catalog.variant",
            ),
        ),
    ]
