# Generated by Django 5.2.17 on 2026-10-03 23:41

import django.db.models.deletion
from django.conf import settings
from datetime import timedelta

from django.conf import settings as dj_settings
from django.db import migrations, models


def backfill_due_dates(apps, schema_editor):
    Invoice = apps.get_model("sales", "Invoice")
    days = getattr(dj_settings, "INVOICE_DUE_DAYS", 7)
    for inv in Invoice.objects.filter(due_date__isnull=True).only("id", "date", "source", "period_start"):
        due = inv.period_start if inv.source == "rental" and inv.period_start else inv.date + timedelta(days=days)
        Invoice.objects.filter(pk=inv.pk).update(due_date=due)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_move_repair_invoices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cancel_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Payment link sent", "Payment link sent"),
                    ("Overdue", "Overdue"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Payment link sent",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_due_dates, migrations.RunPython.noop),
    ]
