# Generated by Django 5.2.17 on 2026-10-03 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_due_date_and_cancel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_advance",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Payment link sent", "Payment link sent"),
                    ("Overdue", "Overdue"),
                    ("Cancelled", "Cancelled"),
                    ("Refunded", "Refunded"),
                ],
                default="Payment link sent",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("method", models.CharField(max_length=40)),
                ("reference", models.CharField(blank=True, max_length=80)),
                ("reason", models.CharField(max_length=200)),
                ("refunded_on", models.DateField()),
                (
                    "restocked",
                    models.BooleanField(
                        default=False,
                        help_text="Returned units were put back into stock.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="sales.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RefundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.PositiveIntegerField()),
                (
                    "invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_items",
                        to="sales.invoiceitem",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.refund",
                    ),
                ),
            ],
        ),
    ]
