# Generated by Django 6.1.1 on 2026-09-07 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('repairs', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Sales', 'Sales'), ('Repair', 'Repair'), ('Rental', 'Rental'), ('Other', 'Other')], max_length=10)),
                ('item_label', models.CharField(help_text="What the warranty actually covers, e.g. 'Dell Latitude 5420' or 'Screen replacement'.", max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to='sales.invoice')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='parties.party')),
                ('repair_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to='repairs.repairticket')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
